#!/bin/bash

sudo apt install -y xmonad xmobar stalonetray xautolock xscreensaver gnome-screensaver imwheel xfce4-power-manager feh xcompmgr shutter dmenu xdotool wmctrl tlp

echo 'Cloning xmonad-pulsevolume'
git clone git@github.com:bchurchill/xmonad-pulsevolume.git ~/.xmonad-pulsevolume

echo 'Symlinking xmobar config...'
ln -sf `readlink -f ./xmobarrc` ~/.xmobarrc

echo 'Symlinking stalonebar config...'
ln -s `readlink -f ./stalonetrayrc` ~/.stalonetrayrc
