#!/bin/bash

function runOnce() {
    if [ -z "$(pgrep $1)" ]; then
        $@ &
    fi
}

# Network Manager
runOnce nm-applet

# XComposite
runOnce xcompmgr -c

# Screensaver
#   other options:
#     cinnamon-settings-daemon
#     xscreensaver -no-splash
runOnce gnome-screensaver
  
# xfce4-power-manager sometimes conflicts with the indicator-power package
runOnce xfce4-power-manager --no-daemon

# Background cycler
runOnce ~/.xmonad/scripts/background_cycler.sh

# Disable touchpad tap click
runOnce xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Tap Action" 0

# Increase mouse speed a tad
runOnce xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Accel Constant Deceleration" 2

# stalonetray for notification icons (nm-applet, pidgin, etc)
runOnce stalonetray

# Shutter for screenshots
runOnce shutter --min_at_startup

# Pidgin
runOnce pidgin

# Default Browser
runOnce `update-alternatives --query x-www-browser | grep "Value:" | awk '{print $2}'`

# Gnome Authentication Agent so apps can request sudo access
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

if [ -e ./startup-private ]; then
  ./startup-private
fi

